site_name: Shimming-toolbox
theme:
  name: readthedocs
repo_url: https://github.com/shimming-toolbox/shimming-toolbox
docs_dir: ./docs
markdown_extensions:
  - admonition
  - extra:
  - nl2br:
extra_css:
  - css/extra.css
nav:
